variables:
    PLUGIN_NAME : 'cookiesConsent'

include:
  - project: 'documentacao-e-tarefas/modelosparaintegracaocontinua'
    ref: main
    file:
      - 'templates/groups/pkp_plugin.yml'
      - 'templates/groups/ops_plugins_cypress_tests_model.yml'

integration_tests:
  before_script:
    - export CYPRESS_adminUser="admin"
    - export CYPRESS_adminPassword="admin"
    - export CYPRESS_context="publicknowledge"